apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: patrn-ink

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: patrn-ui
  app.kubernetes.io/component: frontend
  app.kubernetes.io/part-of: patrn-ink
