apiVersion: v1
kind: Service
metadata:
  name: patrn-ui
  namespace: patrn-ink
  labels:
    app: patrn-ui
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: patrn-ui
    component: frontend
  ports:
    - name: http
      port: 80
      targetPort: 3000
