apiVersion: v1
kind: Service
metadata:
  name: patrn-api
  namespace: patrn-ink
  labels:
    app: patrn-api
    component: backend
spec:
  type: ClusterIP
  selector:
    app: patrn-api
    component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
